
package VistaAdmin;

import Conexion.ConexionSQL;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Blob;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/*
 * @author Davis
 */
public class PanelPelicula extends javax.swing.JPanel {

    DefaultTableModel model;
    public static int idPeli = 0, idCategoriaPelicula=0, cantidadPeli = 0;
    public static double costoPeli = 0;
    public static String tipoPelicula = "", nombrePeli="";
    public static boolean mostrarPelicula = false;

    public PanelPelicula() {
        initComponents();
        cargar();
    }
    
    void cargar(){     
        String mostrar="SELECT * FROM Pelicula WHERE estadoP="+1;
        String []titulos={"id","Imagen","Película","Costo","Stock"};
        Object []Registros=new Object[5];
        
        model= new DefaultTableModel(null, titulos);
        
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(mostrar);

            tablaMostrarPelicula.setDefaultRenderer(Object.class, new TablaPelicula());

            while(rs.next())
            {
              Registros[0] = rs.getString(1);

              Blob foto = rs.getBlob(6);
              byte[] data = foto.getBytes(1, (int) foto.length());
              BufferedImage img = null;

              try {
                  img = ImageIO.read(new ByteArrayInputStream(data));
              } catch (Exception e) {
                  System.out.println("error imagen pelicula " + e);
              }

                Registros[1]= new JLabel(new ImageIcon(img));
                Registros[2]= rs.getString(2);
                Registros[3]= rs.getString(3);
                Registros[4]= rs.getString(5);  

                model.addRow(Registros);
            }
            tablaMostrarPelicula.setModel(model);
            tablaMostrarPelicula.setRowHeight(170);
        } catch (SQLException ex) {
            System.out.println("Error en la tabla pelicula: " + ex);
        }
    }
    
    void EliminarPelicula(){
        try {
                String insertar = "UPDATE Pelicula SET "
                +"estadoP=2"
                +"WHERE idPelicula='"+idPeli+"'";
                
                PreparedStatement pst = cn.prepareStatement(insertar);
                pst.executeUpdate();
                
                System.out.println("Se elimino correctamente la pelicula");
        } 
        catch (Exception e) {
                System.out.println("error al Eliminar los datos de la pelicula: "+e);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LabelListar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelNuevo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelEliminar = new javax.swing.JLabel();
        LabelEditar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMostrarPelicula = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        LabelListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listar.png"))); // NOI18N
        LabelListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelListarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Listar");

        LabelNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        LabelNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelNuevoMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nuevo");

        LabelEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        LabelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEliminarMouseClicked(evt);
            }
        });

        LabelEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        LabelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEditarMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Editar");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Eliminar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelListar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEditar)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelEliminar)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Lista de Películas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 612, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tablaMostrarPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMostrarPelicula.setGridColor(new java.awt.Color(204, 255, 255));
        tablaMostrarPelicula.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tablaMostrarPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMostrarPeliculaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMostrarPelicula);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LabelListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelListarMouseClicked
        // TODO add your handling code here:
        cargar();
    }//GEN-LAST:event_LabelListarMouseClicked

    private void LabelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelNuevoMouseClicked
        // TODO add your handling code here:
        mostrarPelicula = false;
        tipoPelicula = "NUEVO";
        NuevaPelicula NP = new NuevaPelicula();
        NP.setVisible(true);
    }//GEN-LAST:event_LabelNuevoMouseClicked

    private void LabelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEditarMouseClicked
        // TODO add your handling code here:
        tipoPelicula = "EDITAR";
        if(mostrarPelicula==true){
            NuevaPelicula NP = new NuevaPelicula();
            NP.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe Seleccionar un registro");
        }
    }//GEN-LAST:event_LabelEditarMouseClicked

    private void tablaMostrarPeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMostrarPeliculaMouseClicked
        // TODO add your handling code here:
        String mostrar=(String) tablaMostrarPelicula.getValueAt(tablaMostrarPelicula.getSelectedRow(),0);
        try {
            String ConsultaSQL="SELECT * FROM Pelicula WHERE idPelicula="+mostrar;

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(ConsultaSQL);                    

            if(rs.next()){
                idCategoriaPelicula = rs.getInt("idCategoria");
                nombrePeli = rs.getString("nombreP");
                cantidadPeli = rs.getInt("cantidadP");
                costoPeli = rs.getDouble("costoP");
                idPeli = rs.getInt("idPelicula");
            }
            
            System.out.println(idPeli+"->"+idCategoriaPelicula);

        } catch (Exception e) {
            System.out.println("ERROR seleccionar datos de la pelicula: "+e.getMessage());
        }
        mostrarPelicula = true;
    }//GEN-LAST:event_tablaMostrarPeliculaMouseClicked

    private void LabelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEliminarMouseClicked
        // TODO add your handling code here:
        if(mostrarPelicula==true){
            int reply = JOptionPane.showConfirmDialog(null, "DESEAS ELIMINAR LA PELÍCULA ?", "Eliminar", JOptionPane.YES_NO_OPTION); 
            if (reply == JOptionPane.YES_OPTION) { 
                EliminarPelicula();
            } 
            else { 
                System.out.println("No se elimino :)");
            }            
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
        }
        mostrarPelicula = false;
        cargar();
    }//GEN-LAST:event_LabelEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEditar;
    private javax.swing.JLabel LabelEliminar;
    private javax.swing.JLabel LabelListar;
    private javax.swing.JLabel LabelNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMostrarPelicula;
    // End of variables declaration//GEN-END:variables
    ConexionSQL cc = new ConexionSQL();
    Connection cn= ConexionSQL.conexionn();
}
