
package VistaAdmin;

import java.sql.Connection;
import Conexion.ConexionSQL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * @author Davis
 */
public class PanelClientes extends javax.swing.JPanel {

    DefaultTableModel model;
    
    public static String name = "", apellidoPa = "", apellidoMa = "", Dni = "", Sexo = "", tipoCliente = "";
    public static boolean mostrarCliente = false;
    public static int idCliente = 0;
    
    public PanelClientes() {
        initComponents();
        cargar("");
    }
    
    void cargar(String valor){     
        String mostrar="SELECT * FROM Cliente WHERE estadoCliente="+1;
        String []titulos={"Nombres","Apellidos","DNI","Sexo"};
        String []Registros=new String[4];
        model= new DefaultTableModel(null, titulos);
        String apellido="";
        try {
              Statement st = cn.createStatement();
              ResultSet rs = st.executeQuery(mostrar);
              while(rs.next())
              {
                  Registros[0]= rs.getString("nombre");
                  apellido = rs.getString("apellidoP") + " "+ rs.getString("apellidoM");
                  Registros[1]= apellido;
                  Registros[2]= rs.getString("dni");
                  Registros[3]= rs.getString("sexo");       
                  model.addRow(Registros);
              }
              tablaMostrarCliente.setModel(model);
        } catch (SQLException ex) {
            System.out.println("Error en la tabla cliente: " + ex);
        }
    }
    
    void EliminarCliente(){
        try {
                String insertar = "UPDATE Cliente SET "
                +"estadoCliente=2"
                +"WHERE idCliente='"+idCliente+"'";
                
                PreparedStatement pst = cn.prepareStatement(insertar);
                pst.executeUpdate();

            } catch (Exception e) {
                System.out.println("error al Eliminar los datos del Cliente: "+e);
            } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LabelListar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelNuevo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelEliminar = new javax.swing.JLabel();
        LabelEditar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMostrarCliente = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Lista de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        LabelListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listar.png"))); // NOI18N
        LabelListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelListarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Listar");

        LabelNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        LabelNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelNuevoMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nuevo");

        LabelEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        LabelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEliminarMouseClicked(evt);
            }
        });

        LabelEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        LabelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEditarMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Editar");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Eliminar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelListar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEditar)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelEliminar)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaMostrarCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tablaMostrarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMostrarCliente.setGridColor(new java.awt.Color(204, 255, 255));
        tablaMostrarCliente.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tablaMostrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMostrarClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMostrarCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LabelListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelListarMouseClicked
        // TODO add your handling code here:
        cargar("");
    }//GEN-LAST:event_LabelListarMouseClicked

    private void tablaMostrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMostrarClienteMouseClicked
        // TODO add your handling code here:
        String mostrar=(String) tablaMostrarCliente.getValueAt(tablaMostrarCliente.getSelectedRow(),2);
        try {
            String ConsultaSQL="SELECT * FROM Cliente WHERE dni='"+mostrar+"'";

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(ConsultaSQL);                    

            if(rs.next()){
                name = rs.getString("nombre");
                apellidoPa = rs.getString("apellidoP");
                apellidoMa = rs.getString("apellidoM");
                Dni = rs.getString("dni");
                Sexo = rs.getString("sexo");
                idCliente = rs.getInt("idCliente");
            }  

        } catch (Exception e) {
            System.out.println("ERROR seleccionar datos del Cliente: "+e.getMessage());
        }
        mostrarCliente = true;
    }//GEN-LAST:event_tablaMostrarClienteMouseClicked

    private void LabelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelNuevoMouseClicked
        // TODO add your handling code here:
        mostrarCliente = false;
        tipoCliente = "NUEVO";
        NuevoCliente NC = new NuevoCliente();
        NC.setVisible(true);      
    }//GEN-LAST:event_LabelNuevoMouseClicked

    private void LabelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEditarMouseClicked
        // TODO add your handling code here:
        tipoCliente = "EDITAR";
        if(mostrarCliente==true){
            NuevoCliente NC = new NuevoCliente();
            NC.setVisible(true);           
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
        }  
        cargar("");
    }//GEN-LAST:event_LabelEditarMouseClicked

    private void LabelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEliminarMouseClicked
        // TODO add your handling code here:
        if(mostrarCliente==true){
            int reply = JOptionPane.showConfirmDialog(null, "DESEAS ELIMINAR CLIENTE ?", "Eliminar", JOptionPane.YES_NO_OPTION); 
            if (reply == JOptionPane.YES_OPTION) { 
                EliminarCliente();
            } 
            else { 
                System.out.println("No se elimino :)");
            }            
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
        }
        mostrarCliente = false;
        cargar("");
    }//GEN-LAST:event_LabelEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEditar;
    private javax.swing.JLabel LabelEliminar;
    private javax.swing.JLabel LabelListar;
    private javax.swing.JLabel LabelNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMostrarCliente;
    // End of variables declaration//GEN-END:variables
    ConexionSQL cc = new ConexionSQL();
    Connection cn= ConexionSQL.conexionn();
}
