
package VistaAdmin;

import Conexion.ConexionSQL;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * @author Davis
 */
public class PanelReportes extends javax.swing.JPanel {

    
    public PanelReportes() {
        initComponents();
    }
    
    void reporteCliente(){
        String archivo = "C:\\Users\\jamt_\\Documents\\NetBeansProjects\\Pro\\ProyectoOjxPeruAdmin\\src\\VistaAdmin\\ReporteCliente.jasper";
        JasperReport jr;
        
        try {
            jr = (JasperReport) JRLoader.loadObjectFromFile(archivo);
            
            JasperPrint jp = JasperFillManager.fillReport(jr, null, cn);
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            jv.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error al visualizar reporte de cliente: " + e);
        }
    }
    
    void reporteTarjeta(){
        String archivo = "C:\\Users\\jamt_\\Documents\\NetBeansProjects\\Pro\\ProyectoOjxPeruAdmin\\src\\VistaAdmin\\ReporteTarjeta.jasper";
        JasperReport jr;
        
        try {
            jr = (JasperReport) JRLoader.loadObjectFromFile(archivo);
            
            JasperPrint jp = JasperFillManager.fillReport(jr, null, cn);
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            jv.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error al visualizar reporte de tarjeta: " + e);
        }
    }
    
    void reportePelicula(){
        String archivo = "C:\\Users\\jamt_\\Documents\\NetBeansProjects\\Pro\\ProyectoOjxPeruAdmin\\src\\VistaAdmin\\ReportePelicula.jasper";
        JasperReport jr;
        
        try {
            jr = (JasperReport) JRLoader.loadObjectFromFile(archivo);
            
            JasperPrint jp = JasperFillManager.fillReport(jr, null, cn);
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            jv.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error al visualizar reporte de pelicula: " + e);
        }
    }
    
    void reporteAlquiler(){
        String archivo = "C:\\Users\\jamt_\\Documents\\NetBeansProjects\\Pro\\ProyectoOjxPeruAdmin\\src\\VistaAdmin\\ReporteAlquiler.jasper";
        JasperReport jr;
        
        try {
            jr = (JasperReport) JRLoader.loadObjectFromFile(archivo);
            
            JasperPrint jp = JasperFillManager.fillReport(jr, null, cn);
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            jv.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error al visualizar reporte de alquiler: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReporteCliente = new LIB.FSButtonMD();
        btnReporteTarjeta = new LIB.FSButtonMD();
        btnReportePelicula = new LIB.FSButtonMD();
        btnReporteAlquiler = new LIB.FSButtonMD();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        btnReporteCliente.setText("Clientes");
        btnReporteCliente.setFont(new java.awt.Font("Segoe", 1, 18)); // NOI18N
        btnReporteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteClienteActionPerformed(evt);
            }
        });

        btnReporteTarjeta.setText("Tarjetas");
        btnReporteTarjeta.setFont(new java.awt.Font("Segoe", 1, 18)); // NOI18N
        btnReporteTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteTarjetaActionPerformed(evt);
            }
        });

        btnReportePelicula.setText("Peliculas");
        btnReportePelicula.setFont(new java.awt.Font("Segoe", 1, 18)); // NOI18N
        btnReportePelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePeliculaActionPerformed(evt);
            }
        });

        btnReporteAlquiler.setText("Alquiler");
        btnReporteAlquiler.setFont(new java.awt.Font("Segoe", 1, 18)); // NOI18N
        btnReporteAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteAlquilerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporteAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(btnReporteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporteTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporteAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteClienteActionPerformed
        // TODO add your handling code here:
        reporteCliente();
    }//GEN-LAST:event_btnReporteClienteActionPerformed

    private void btnReporteTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteTarjetaActionPerformed
        // TODO add your handling code here:
        reporteTarjeta();
    }//GEN-LAST:event_btnReporteTarjetaActionPerformed

    private void btnReportePeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePeliculaActionPerformed
        // TODO add your handling code here:
        reportePelicula();
    }//GEN-LAST:event_btnReportePeliculaActionPerformed

    private void btnReporteAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteAlquilerActionPerformed
        // TODO add your handling code here:
        reporteAlquiler();
    }//GEN-LAST:event_btnReporteAlquilerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnReporteAlquiler;
    private LIB.FSButtonMD btnReporteCliente;
    private LIB.FSButtonMD btnReportePelicula;
    private LIB.FSButtonMD btnReporteTarjeta;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    ConexionSQL cc = new ConexionSQL();
    Connection cn= ConexionSQL.conexionn();
}
